
DROP TABLE CUSTOMER_BIKE;
DROP TABLE CUSTOMERS;
DROP TABLE BICYCLES;

CREATE TABLE "BICYCLES"
(	"SERIALNUMBER" NUMBER(*,0),
  "MODELTYPE" VARCHAR2(50 BYTE), 
	"PAINTID" NUMBER(*,0), 
	"FRAMESIZE" NUMBER, 
	"ORDERDATE" DATE, 
	"STARTDATE" DATE, 
	"SHIPDATE" DATE, 
	"CONSTRUCTION" VARCHAR2(50 BYTE), 
	"LISTPRICE" NUMBER(38,4), 
	"SALEPRICE" NUMBER(38,4), 
	"SALESTAX" NUMBER(38,4), 
	"SALESTATE" VARCHAR2(50 BYTE)
);

CREATE TABLE "CUSTOMERS" 
(	"CUSTOMERID" NUMBER(*,0), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"ZIPCODE" VARCHAR2(50 BYTE)
);

CREATE TABLE "CUSTOMER_BIKE"
( "CUSTOMERID" NUMBER(*,0),
  "SERIALNUMBER"   NUMBER(38,0)
);

DROP PACKAGE BODY BIKESHOP;
DROP PACKAGE BIKESHOP;

