/*
            SYDNI WARD
            PROJECT 2
            04/01/2021
*/

EXECUTE BIKESHOP.ARCHIVE_CUSTOMER_BIKES; 
EXECUTE BIKESHOP.EXTRACT_BICYCLES('S');
EXECUTE BIKESHOP.EXTRACT_CUSTOMERS('S');
EXECUTE BIKESHOP.EXTRACT_BICYCLES('D');
EXECUTE BIKESHOP.EXTRACT_CUSTOMERS('D');
